data_directory: "../../data/VOC2012"
train_set_path: "ImageSets/Segmentation/train.txt"
validation_set_path: "ImageSets/Segmentation/val.txt"

categories:
    ['background',
    'aeroplane',
    'bicycle',
    'bird',
    'boat',
    'bottle',
    'bus',
    'car',
    'cat',
    'chair',
    'cow',
    'diningtable',
    'dog',
    'horse',
    'motorbike',
    'person',
    'pottedplant',
    'sheep',
    'sofa',
    'train',
    'tvmonitor']

log_path: "/tmp/voc_fcn.html"

size_factor: 32


train:
    epochs: 10